### ISSUE TITLE
Building container fails step 26/39 w/gpg: keyserver receive failed: No data

### ISSUE THREAD

**Issue by ElijahLynn** [jokersoft/docker-jenkins-slave-php-7.2.4#1] opened 2019-02-23 00:15 UTC
This is the failed command, which works fine on my host but fails in the container build process, still investigating:

`gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 1729F83938DA44E27BA0F4D3DBDB397470D12172
`
https://github.com/jokersoft/docker-jenkins-slave-php-7.2.4/blob/b89b82aab959d47ffe46623b451badab31112804/Dockerfile#L73-L75
```
Step 26/39 : RUN set -xe     echo "jenkins ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers  && cd /usr/src  && curl -fSL "https://secure.php.net/get/$PHP_FILENAME/from/this/mirror" -o php.tar.xz  && echo "$PHP_SHA256
*php.tar.xz" | sha256sum -c -   && curl -fSL "https://secure.php.net/get/$PHP_FILENAME.asc/from/this/mirror" -o php.tar.xz.asc  && export GNUPGHOME="$(mktemp -d)"      && for key in $GPG_KEYS; do             gpg -
-keyserver ha.pool.sks-keyservers.net --recv-keys "$key";       done    && gpg --batch --verify php.tar.xz.asc php.tar.xz       && rm -r "$GNUPGHOME"                                                               
 ---> Running in 25b9971b31a7
+ cd /usr/src
+ curl -fSL https://secure.php.net/get/php-7.2.4.tar.xz/from/this/mirror -o php.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     1    0     1    0     0      1      0 --:--:-- --:--:-- --:--:--     1
100   185  100   185    0     0    113      0  0:00:01  0:00:01 --:--:--   249
100 11.4M    0 11.4M    0     0  2636k      0 --:--:--  0:00:04 --:--:-- 4665k
+ echo 7916b1bd148ddfd46d7f8f9a517d4b09cd8a8ad9248734e7c8dd91ef17057a88 *php.tar.xz
+ sha256sum -c -
php.tar.xz: OK
+ curl -fSL https://secure.php.net/get/php-7.2.4.tar.xz.asc/from/this/mirror -o php.tar.xz.asc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     1    0     1    0     0      1      0 --:--:-- --:--:-- --:--:--     1
100   185  100   185    0     0    110      0  0:00:01  0:00:01 --:--:--   774
100   801    0   801    0     0    415      0 --:--:--  0:00:01 --:--:--   415
+ mktemp -d
+ export GNUPGHOME=/tmp/tmp.bT6HkSp90b
+ gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 1729F83938DA44E27BA0F4D3DBDB397470D12172
gpg: keybox '/tmp/tmp.bT6HkSp90b/pubring.kbx' created
gpg: keyserver receive failed: No data
+ gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B1B44D8F021E4E2D6021E995DC9FF8D3EE5AF27F
gpg: keyserver receive failed: No data
The command '/bin/sh -c set -xe     echo "jenkins ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers   && cd /usr/src  && curl -fSL "https://secure.php.net/get/$PHP_FILENAME/from/this/mirror" -o php.tar.xz  && echo "$PHP
_SHA256 *php.tar.xz" | sha256sum -c -   && curl -fSL "https://secure.php.net/get/$PHP_FILENAME.asc/from/this/mirror" -o php.tar.xz.asc  && export GNUPGHOME="$(mktemp -d)"      && for key in $GPG_KEYS; do         g
pg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key";   done    && gpg --batch --verify php.tar.xz.asc php.tar.xz       && rm -r "$GNUPGHOME"' returned a non-zero code: 2                                  ```

**Comment by ElijahLynn** [comment] 2019-02-23 00:19
Actual error inside container is 
> root@298b7430ed27:~# gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 1729F83938DA44E27BA0F4D3DBDB397470D12172
gpg: directory '/home/jenkins/.gnupg' created
gpg: keybox '/home/jenkins/.gnupg/pubring.kbx' created
gpg: keyserver receive failed: Cannot assign requested address

**Comment by ElijahLynn** [comment] 2019-02-23 00:37
Got it, PR coming... 

https://github.com/inversepath/usbarmory-debian-base_image/issues/9#issuecomment-451635505

**Comment by jokersoft** [comment] 2019-02-23 15:12
Still failing with:
```
Step 21/31 : RUN set -xe && mkdir ~/.gnupg && echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf && echo "jenkins ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers && cd /usr/src && curl -fSL "https://secure.php.net/get/$PHP_FILENAME/from/this/mirror" -o php.tar.xz && echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c - && curl -fSL "https://secure.php.net/get/$PHP_FILENAME.asc/from/this/mirror" -o php.tar.xz.asc && export GNUPGHOME="$(mktemp -d)" && for key in $GPG_KEYS; do gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; done && gpg --batch --verify php.tar.xz.asc php.tar.xz && rm -r "$GNUPGHOME"
---> Running in 15c6669c6060
+ mkdir /home/jenkins/.gnupg
+ echo disable-ipv6
+ echo jenkins ALL=(ALL:ALL) NOPASSWD: ALL
+ cd /usr/src
+ curl -fSL https://secure.php.net/get/php-7.2.4.tar.xz/from/this/mirror -o php.tar.xz
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 1 0 1 0 0 1 0 --:--:-- --:--:-- --:--:-- 1
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 185 100 185 0 0 128 0 0:00:01 0:00:01 --:--:-- 232
100 65299 0 65299 0 0 38292 0 --:--:-- 0:00:01 --:--:-- 38292
100 9039k 0 9039k 0 0 3415k 0 --:--:-- 0:00:02 --:--:-- 9528k
100 11.4M 0 11.4M 0 0 4226k 0 --:--:-- 0:00:02 --:--:-- 10.6M
+ sha256sum -c -
+ echo 7916b1bd148ddfd46d7f8f9a517d4b09cd8a8ad9248734e7c8dd91ef17057a88 *php.tar.xz
php.tar.xz: OK
+ curl -fSL https://secure.php.net/get/php-7.2.4.tar.xz.asc/from/this/mirror -o php.tar.xz.asc
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 1 0 1 0 0 2 0 --:--:-- --:--:-- --:--:-- 2
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 185 100 185 0 0 209 0 --:--:-- --:--:-- --:--:-- 528
100 801 0 801 0 0 765 0 --:--:-- 0:00:01 --:--:-- 765
+
mktemp -d
+ export GNUPGHOME=/tmp/tmp.g47TJidkn3
+ gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 1729F83938DA44E27BA0F4D3DBDB397470D12172
gpg: keybox '/tmp/tmp.g47TJidkn3/pubring.kbx' created
gpg: keyserver receive failed: Cannot assign requested address
+ gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B1B44D8F021E4E2D6021E995DC9FF8D3EE5AF27F
gpg: keyserver receive failed: Cannot assign requested address
```

investigation required.

**Comment by ElijahLynn** [comment] 2019-02-25 19:02
Reproduced. Interesting that if I build the image only up to that point then run the container and exec into it and run commands manually it works fine. I wonder if it needs a sleep.

**Comment by ElijahLynn** [comment] 2019-02-25 19:30
Getting interesting, mixed results running the for loop inside the container though, sometimes it works sometimes it doesn't. Will play with more later, no time right now.

**Comment by sklabinsky** [comment] 2019-02-26 08:53
Same here - reproduced, but could not find the reason. Will investigate in a free time.

**Comment by sklabinsky** [comment] 2019-02-26 11:31
Managed to fix here: https://github.com/jokersoft/docker-jenkins-slave-php-7.2.4/pull/4

**Comment by jokersoft** [comment] 2019-02-26 13:16
Resolved by using multiple sources.

**Closed as completed by jokersoft** 2019-02-26 13:16 UTC
Labels: bug, help wanted

**Comment by ElijahLynn** [comment] 2019-02-26 17:31
Nice, thanks!
